const QC_CONFIG = {
  "SHE": {
    "EHS Overview": ["Safety equipment", "Personal Protective Equipment (PPE)", "Site safety signs"]
  },
  "Before": {
    "Before On Tower Sector A": ["Tower view before installation Sector A"],
    "Before On Tower Sector B": ["Tower view before installation Sector B"],
    "Before On Tower Sector C": ["Tower view before installation Sector C"],
    "Before On Tower Sector D": ["Tower view before installation Sector D"],
    "Before On Ground": ["Ground area before installation"],
    "Before On Ground C1": ["Ground area C1 before installation"],
    "Before On Ground C2": ["Ground area C2 before installation"]
  },
  "Panorama": {
    "0° Panorama": ["Panoramic view at 0 degrees"],
    "30° Panorama": ["Panoramic view at 30 degrees"],
    "60° Panorama": ["Panoramic view at 60 degrees"],
    "90° Panorama": ["Panoramic view at 90 degrees"],
    "120° Panorama": ["Panoramic view at 120 degrees"],
    "150° Panorama": ["Panoramic view at 150 degrees"],
    "180° Panorama": ["Panoramic view at 180 degrees"],
    "210° Panorama": ["Panoramic view at 210 degrees"],
    "240° Panorama": ["Panoramic view at 240 degrees"],
    "270° Panorama": ["Panoramic view at 270 degrees"],
    "300° Panorama": ["Panoramic view at 300 degrees"],
    "330° Panorama": ["Panoramic view at 330 degrees"]
  },
  "Quality Check": {
    "Sector A": {
      "ระบุ Sector ที่ติดตั้ง": "Confirming Sector A installation",
      "ระบุคลื่นความถี่ที่ทำการติดตั้ง": "Frequency identification",
      "Tower Outdoor View": "General view of the tower",
      "Antenna/AAU position": "Correct positioning of Antenna/AAU",
      "Antenna Model": "Readable antenna model label",
      "M Tilt": "Mechanical tilt setting check",
      "Azimuth with Compass": "Compass showing azimuth direction",
      "Zoom Compass of Azimuth Sector A": "Close-up of compass reading",
      "Jumper/ RET under Antenna/AAU photo include Filter/Combiner/Triplexer": "Cable and peripheral connections",
      "Clamp Antenna / AAU Top/Bottom": "Clamping status top and bottom",
      "RRU#1 Overview Photo": "Overview of first RRU",
      "RRU#1 Serial": "Serial number of RRU#1",
      "Ground cable connect under RRU#1": "Grounding check for RRU#1",
      "Jumper/RET/Label/Color mark under RRU#1": "Labeling and color marking RRU#1",
      "RRU#1/AAU Socket Wire strip length is 18mm with scale": "Wire strip length measurement with ruler (18mm)",
      "RRU#1/AAU Socket Left Side view": "Left socket view",
      "RRU#1/AAU Socket Right Side view": "Right socket view",
      "Open RRU#1 cover with plug in CPRI and socket DC RRU#1 Sector A": "Internal connections of RRU#1",
      "RRU#2 Overview Photo": "Overview of second RRU",
      "RRU#2 Serial": "Serial number of RRU#2",
      "Ground cable connect under RRU#2": "Grounding check for RRU#2",
      "Jumper/RET/Label/Color mark under RRU#2": "Labeling and color marking RRU#2",
      "RRU#2/AAU Socket Wire strip length is 18mm with scale": "Wire strip length measurement with ruler (18mm) RRU#2",
      "RRU#2/AAU Socket Left Side view": "Left socket view RRU#2",
      "RRU#2/AAU Socket Right Side view": "Right socket view RRU#2",
      "Open RRU#2 cover with plug in CPRI and socket DC RRU#2 Sector A": "Internal connections of RRU#2",
      "Stainless cable tie at jumper with pipe": "Cable tie application",
      "DCDU socket of RRU Sector A#1, After wire strip at DCDU": "DCDU connection check",
      "OCB": "Over-current breaker check",
      "Mounting": "Mounting stability",
      "Ground bar": "Ground bar connection",
      "Notch CPRI Cable": "CPRI cable routing",
      "(if any) Filter": "Filter installation (if applicable)",
      "(if any) Pipe": "Pipe installation (if applicable)",
      "(if any) Diplexer / Combiner / Splitter": "Peripheral components"
    },
    "Sector B": {
      "ระบุ Sector ที่ติดตั้ง": "Confirming Sector B installation",
      "ระบุคลื่นความถี่ที่ทำการติดตั้ง": "Frequency identification",
      "Tower Outdoor View": "General view of the tower",
      "Antenna/AAU position": "Correct positioning",
      "Antenna Model": "Antenna model label",
      "M Tilt": "Mechanical tilt check",
      "Azimuth with Compass": "Compass azimuth",
      "Zoom Compass of Azimuth Sector A": "Zoomed compass reading",
      "Jumper/ RET under Antenna/AAU photo include Filter/Combiner/Triplexer": "Jumper and peripheral connections",
      "Clamp Antenna / AAU Top/Bottom": "Clamping status",
      "RRU#1 Overview Photo": "RRU#1 Overview",
      "RRU#1 Serial": "RRU#1 Serial number",
      "Ground cable connect under RRU#1": "RRU#1 Grounding",
      "Jumper/RET/Label/Color mark under RRU#1": "RRU#1 Labeling",
      "RRU#1/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#1",
      "RRU#1/AAU Socket Left Side view": "Left socket RRU#1",
      "RRU#1/AAU Socket Right Side view": "Right socket RRU#1",
      "Open RRU#1 cover with plug in CPRI and socket DC RRU#1 Sector A": "Internal RRU#1",
      "RRU#2 Overview Photo": "RRU#2 Overview",
      "RRU#2 Serial": "RRU#2 Serial number",
      "Ground cable connect under RRU#2": "RRU#2 Grounding",
      "Jumper/RET/Label/Color mark under RRU#2": "RRU#2 Labeling",
      "RRU#2/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#2",
      "RRU#2/AAU Socket Left Side view": "Left socket RRU#2",
      "RRU#2/AAU Socket Right Side view": "Right socket RRU#2",
      "Open RRU#2 cover with plug in CPRI and socket DC RRU#2 Sector A": "Internal RRU#2",
      "Stainless cable tie at jumper with pipe": "Cable ties",
      "DCDU socket of RRU Sector A#1, After wire strip at DCDU": "DCDU socket",
      "OCB": "OCB",
      "Mounting": "Mounting",
      "Ground bar": "Ground bar",
      "Notch CPRI Cable": "CPRI Cable",
      "(if any) Filter": "Filter",
      "(if any) Pipe": "Pipe",
      "(if any) Diplexer / Combiner / Splitter": "Diplexer/Combiner/Splitter"
    },
    "Sector C": {
      "ระบุ Sector ที่ติดตั้ง": "Confirming Sector C installation",
      "ระบุคลื่นความถี่ที่ทำการติดตั้ง": "Frequency identification",
      "Tower Outdoor View": "Tower View",
      "Antenna/AAU position": "Antenna Position",
      "Antenna Model": "Antenna Model Label",
      "M Tilt": "Tilt check",
      "Azimuth with Compass": "Azimuth compass",
      "Zoom Compass of Azimuth Sector A": "Zoomed Azimuth",
      "Jumper/ RET under Antenna/AAU photo include Filter/Combiner/Triplexer": "Cable connections",
      "Clamp Antenna / AAU Top/Bottom": "Clamping",
      "RRU#1 Overview Photo": "RRU#1 Overview",
      "RRU#1 Serial": "RRU#1 Serial",
      "Ground cable connect under RRU#1": "RRU#1 Grounding",
      "Jumper/RET/Label/Color mark under RRU#1": "RRU#1 Labeling",
      "RRU#1/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#1",
      "RRU#1/AAU Socket Left Side view": "Left socket RRU#1",
      "RRU#1/AAU Socket Right Side view": "Right socket RRU#1",
      "Open RRU#1 cover with plug in CPRI and socket DC RRU#1 Sector A": "Internal RRU#1",
      "RRU#2 Overview Photo": "RRU#2 Overview",
      "RRU#2 Serial": "RRU#2 Serial",
      "Ground cable connect under RRU#2": "RRU#2 Grounding",
      "Jumper/RET/Label/Color mark under RRU#2": "RRU#2 Labeling",
      "RRU#2/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#2",
      "RRU#2/AAU Socket Left Side view": "Left socket RRU#2",
      "RRU#2/AAU Socket Right Side view": "Right socket RRU#2",
      "Open RRU#2 cover with plug in CPRI and socket DC RRU#2 Sector A": "Internal RRU#2",
      "Stainless cable tie at jumper with pipe": "Cable ties",
      "DCDU socket of RRU Sector A#1, After wire strip at DCDU": "DCDU socket",
      "OCB": "OCB",
      "Mounting": "Mounting",
      "Ground bar": "Ground bar",
      "Notch CPRI Cable": "CPRI Cable",
      "(if any) Filter": "Filter",
      "(if any) Pipe": "Pipe",
      "(if any) Diplexer / Combiner / Splitter": "Diplexer/Combiner/Splitter"
    },
    "Sector D": {
      "ระบุ Sector ที่ติดตั้ง": "Confirming Sector D installation",
      "ระบุคลื่นความถี่ที่ทำการติดตั้ง": "Frequency identification",
      "Tower Outdoor View": "Tower View",
      "Antenna/AAU position": "Antenna Position",
      "Antenna Model": "Antenna Model Label",
      "M Tilt": "Tilt check",
      "Azimuth with Compass": "Azimuth compass",
      "Zoom Compass of Azimuth Sector A": "Zoomed Azimuth",
      "Jumper/ RET under Antenna/AAU photo include Filter/Combiner/Triplexer": "Cable connections",
      "Clamp Antenna / AAU Top/Bottom": "Clamping",
      "RRU#1 Overview Photo": "RRU#1 Overview",
      "RRU#1 Serial": "RRU#1 Serial",
      "Ground cable connect under RRU#1": "RRU#1 Grounding",
      "Jumper/RET/Label/Color mark under RRU#1": "RRU#1 Labeling",
      "RRU#1/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#1",
      "RRU#1/AAU Socket Left Side view": "Left socket RRU#1",
      "RRU#1/AAU Socket Right Side view": "Right socket RRU#1",
      "Open RRU#1 cover with plug in CPRI and socket DC RRU#1 Sector A": "Internal RRU#1",
      "RRU#2 Overview Photo": "RRU#2 Overview",
      "RRU#2 Serial": "RRU#2 Serial",
      "Ground cable connect under RRU#2": "RRU#2 Grounding",
      "Jumper/RET/Label/Color mark under RRU#2": "RRU#2 Labeling",
      "RRU#2/AAU Socket Wire strip length is 18mm with scale": "Wire strip 18mm RRU#2",
      "RRU#2/AAU Socket Left Side view": "Left socket RRU#2",
      "RRU#2/AAU Socket Right Side view": "Right socket RRU#2",
      "Open RRU#2 cover with plug in CPRI and socket DC RRU#2 Sector A": "Internal RRU#2",
      "Stainless cable tie at jumper with pipe": "Cable ties",
      "DCDU socket of RRU Sector A#1, After wire strip at DCDU": "DCDU socket",
      "OCB": "OCB",
      "Mounting": "Mounting",
      "Ground bar": "Ground bar",
      "Notch CPRI Cable": "CPRI Cable",
      "(if any) Filter": "Filter",
      "(if any) Pipe": "Pipe",
      "(if any) Diplexer / Combiner / Splitter": "Diplexer/Combiner/Splitter"
    },
    "On Ground": {
      "Site Overview": "General view of the entire site",
      "Tower/Pole 1": "View of tower or pole 1",
      "Tower/Pole 2": "View of tower or pole 2",
      "Tower/Pole 3": "View of tower or pole 3",
      "Master Bar Ground#1": "Master grounding bar 1",
      "Master Bar Ground#2": "Master grounding bar 2",
      "Kilowat Hour Meter": "Electricity meter photo"
    },
    "On Ground C1": {
      "Main Breaker of AC MDB#1.1": "Main AC breaker 1.1",
      "Main Breaker of AC MDB#1.2": "Main AC breaker 1.2",
      "POE/POR Open Rack": "Open rack overview",
      "All Cabinet Overview": "All cabinets overview",
      "Rectifier View Photo": "Rectifier overview",
      "BUSBAR : Breaker DC-RRU": "Busbar and DC breakers",
      "Bayface of BBU": "BBU front view",
      "Ground Cable of BBU": "BBU grounding cable",
      "Ground Cable of BBU to Ground Bar in Cabinet": "BBU grounding connection",
      "DCDU : DC-RRU": "DCDU overview",
      "Ground Cable of DCDU": "DCDU grounding cable",
      "Ground Cable of DCDU to Ground Bar in Cabinet": "DCDU grounding connection",
      "Serial of BBU": "BBU Serial number",
      "Zoom Left Side of BBU with Redmark สำหรับการดที่ทำการติดตั้ง": "BBU left zoom with install mark",
      "Zoom Right Side of BBU with Redmark สำหรับการดที่ทำการติดตั้ง": "BBU right zoom with install mark",
      "Serial Card install #1": "Card 1 Serial",
      "Serial Card install #2": "Card 2 Serial",
      "Serial UPEU": "UPEU Serial",
      "Copper Socket DC-BBU@DCDU with scale Socket 1": "DC socket 1 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 2": "DC socket 2 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 3": "DC socket 3 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 4": "DC socket 4 measurement",
      "Display Current Load": "Load display reading",
      "Bar Ground in Cabinet": "Cabinet grounding bar",
      "Alarm Krone": "Krone alarm block",
      "POE Intlet": "POE inlet connection",
      "POE Outlet": "POE outlet connection",
      "ROOM Intlet": "Room inlet",
      "ROOM Outlet": "Room outlet",
      "Position Loop CPRI with J-hanger at outdoor POE": "CPRI loop with J-hanger",
      "Wiring CPRI with Feeder (Vertical)": "CPRI and feeder wiring",
      "Grounding kit position showing installation After insulation/water proofing tape to see that the kit are connect to shield ground.": "Grounding kit installation details",
      "Feeder Overview": "Feeder cables overview",
      "Notch CPRI Cable": "CPRI cable routing",
      "GPS Antenna Installation": "GPS antenna",
      "GPS Surge Installation": "GPS surge protection",
      "GPS Wiring Cable": "GPS wiring",
      "GPS check photo, screenshot GPS status from OMC": "GPS status screenshot",
      "Label in door": "Inside door label",
      "Label Outdoor": "Outdoor label",
      "Site Cleaness": "Overall site cleanliness"
    },
    "On Ground C2": {
       "Main Breaker of AC MDB#1.1": "Main AC breaker 1.1",
      "Main Breaker of AC MDB#1.2": "Main AC breaker 1.2",
      "POE/POR Open Rack": "Open rack overview",
      "All Cabinet Overview": "All cabinets overview",
      "Rectifier View Photo": "Rectifier overview",
      "BUSBAR : Breaker DC-RRU": "Busbar and DC breakers",
      "Bayface of BBU": "BBU front view",
      "Ground Cable of BBU": "BBU grounding cable",
      "Ground Cable of BBU to Ground Bar in Cabinet": "BBU grounding connection",
      "DCDU : DC-RRU": "DCDU overview",
      "Ground Cable of DCDU": "DCDU grounding cable",
      "Ground Cable of DCDU to Ground Bar in Cabinet": "DCDU grounding connection",
      "Serial of BBU": "BBU Serial number",
      "Zoom Left Side of BBU with Redmark สำหรับการดที่ทำการติดตั้ง": "BBU left zoom with install mark",
      "Zoom Right Side of BBU with Redmark สำหรับการดที่ทำการติดตั้ง": "BBU right zoom with install mark",
      "Serial Card install #1": "Card 1 Serial",
      "Serial Card install #2": "Card 2 Serial",
      "Serial UPEU": "UPEU Serial",
      "Copper Socket DC-BBU@DCDU with scale Socket 1": "DC socket 1 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 2": "DC socket 2 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 3": "DC socket 3 measurement",
      "Copper Socket DC-BBU@DCDU with scale Socket 4": "DC socket 4 measurement",
      "Display Current Load": "Load display reading",
      "Bar Ground in Cabinet": "Cabinet grounding bar",
      "Alarm Krone": "Krone alarm block",
      "POE Intlet": "POE inlet connection",
      "POE Outlet": "POE outlet connection",
      "ROOM Intlet": "Room inlet",
      "ROOM Outlet": "Room outlet",
      "Position Loop CPRI with J-hanger at outdoor POE": "CPRI loop with J-hanger",
      "Wiring CPRI with Feeder (Vertical)": "CPRI and feeder wiring",
      "Grounding kit position showing installation After insulation/water proofing tape to see that the kit are connect to shield ground.": "Grounding kit installation details",
      "Feeder Overview": "Feeder cables overview",
      "Notch CPRI Cable": "CPRI cable routing",
      "GPS Antenna Installation": "GPS antenna",
      "GPS Surge Installation": "GPS surge protection",
      "GPS Wiring Cable": "GPS wiring",
      "GPS check photo, screenshot GPS status from OMC": "GPS status screenshot",
      "Label in door": "Inside door label",
      "Label Outdoor": "Outdoor label",
      "Site Cleaness": "Overall site cleanliness"
    }
  },
  "Equipment Checklist": {
    "Photo of all equipment will be install on site": ["All Install Equipment"],
    "Photo of all equipment will be dismantle on site": ["All Dismantle Equipment"]
  }
};
